object Versions {
    const val appcompat = "1.3.1"
    const val chucker = "3.5.2"
    const val constraint = "2.1.1"
    const val coroutines = "1.5.2"
    const val core = "1.6.0"
    const val coreTesting = "2.1.0"
    const val fragment = "1.3.6"
    const val glide = "4.12.0"
    const val gson = "2.8.8"
    const val junit = "4.13.2"
    const val kotlin = "1.6.0"
    const val legacySupport = "1.0.0"
    const val lifecycle = "2.3.1"
    const val mockk = "1.12.0"
    const val navigation = "2.3.5"
    const val okhttp = "4.9.2"
    const val retrofit = "2.9.0"
    const val room = "2.3.0"
    const val sdpAndroid = "1.0.6"
    const val sqliteJdbc = "3.34.0"

    const val classpath_detekt = "1.18.1"
    const val classpath_koin = "2.2.3"
    const val classpath_gradle = "7.0.3"
}
